### ISSUE TITLE
Error in console if you join while votemap is already started

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Reispfannenfresser/partly-adequate-mapvote#10]
**Description**
When you join on started votemap you get this error and the votemap do not load

**How to reproduce**
1. join the server while the votemap is started

**Behaviour**
this error in client-side console
[ERROR] lua/pam/client/extensions/cl_votescreen_dark_api.lua:15: attempt to index upvalue 'panel' (a nil value)
  1. OnVoterAdded - lua/pam/client/extensions/cl_votescreen_dark_api.lua:15
   2. OnVoterAdded - lua/pam/client/cl_extension_handler.lua:76
    3. func - lua/pam/client/cl_networking.lua:30
     4. unknown - lua/includes/extensions/net.lua:32

**Expected Behaviour**
No error and the votemap should loads

**Additional Information**
- which version of PAM do you use?
last version from workshop

**Comment by Reispfannenfresser** [comment]
Thanks for reporting :+1:
I was assuming that such an issue existed, but never tested it and eventually forgot about it.

**Comment by Reispfannenfresser** [comment]
I think this should be fixed now. (I wasn't able to test it yet.)
