### ISSUE TITLE
[GAMEMODE REQUEST] Light Hide and Seek

### ISSUE THREAD

**Issue by nblockbuster** [Reispfannenfresser/partly-adequate-mapvote#11]
- [workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=1852720956) 
- [source](https://github.com/Fafy2801/light-hns)

**Comment by Reispfannenfresser** [comment]
Shouldn't take long. The gamemode seems to have its own api for mapvote addons which is great :+1:

**Comment by nblockbuster** [comment]
alright! thanks so much

**Comment by Reispfannenfresser** [comment]
The new version of PAM is now released (but may still still be buggy)
I've moved support for most gamemodes into [this addon](https://github.com/Partly-Adequate/pam-compatibility-pack)
