### ISSUE TITLE
[FEATURE REQUEST] Random Map Button

### ISSUE THREAD

**Issue by K4iblue** [Reispfannenfresser/partly-adequate-mapvote#12]
**Category**
Ui / QoL

**Description**
A new Voting Option, a "Random Button" kinda like [this](https://i.redd.it/jmrytv4ro4xy.png) on the right hand side. Where if the most users vote for "Random Map", your Addon will choose a random Map, from all available Maps.

**Motivation**
Some Users from my Server requested this idea, this could increase the number of times some "less-known" Maps will get played

**Comment by Reispfannenfresser** [comment]
Thanks for the request,
I'm currently reworking the entire vote system to make it more adjustable. I'll probably add this feature once that's done.

**Comment by Reispfannenfresser** [comment]
The new version of PAM is now released (but may still still be buggy)
There's now a [new addon](https://github.com/Partly-Adequate/pam-random-option) for adding the requested feature to PAM.
