### ISSUE TITLE
Using the search function with Dark Votescreen will cause lua errors

### ISSUE THREAD

**Issue by The1337Gh0st** [Reispfannenfresser/partly-adequate-mapvote#17]
**Description**
Upon using the search function included with the Dark Votescreen, it will cause lua errors.

**How to reproduce**
Using the search function to search for the name of a map will cause lua errors.

**Behaviour**
It causes lua errors to appear in console.

**Expected Behaviour**
There should not be a lua error.

**Additional Information**
I am using PAM version 2.

My settings are:
`prefixes` gm,ttt
`limit` 25
`cooldown` 3
`enabled` true

The error is:
```
[ERROR] lua/pam/client/extensions/dark_votescreen_panel.lua:400: attempt to index field 'winning_option' (a nil value)
  1. RefreshOptionList - lua/pam/client/extensions/dark_votescreen_panel.lua:400
   2. OnChange - lua/pam/client/extensions/dark_votescreen_panel.lua:146
    3. unknown - lua/vgui/dtextentry.lua:206 (x8)
```

**Comment by Reispfannenfresser** [comment]
Thanks for the report.

This was a bug in [pam-dark-votescreen](https://github.com/Partly-Adequate/pam-dark-votescreen)
It should be fixed now 👍🏻
