### ISSUE TITLE
[BUG REPORT] RTV don't work for me

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Reispfannenfresser/partly-adequate-mapvote#4]
**Description**
RTV don't work for me i tried many times, I tried with the command "ttt_pam_rtv" or by writing rtv in chat but nothing happens, obviously "IsEnabled = true"

**How to reproduce**
I thinks is a personal bug or issue 

**Behaviour**
The participation of rock the vote on chat simply does not appear / does not work

**Expected Behaviour**
It should appear/work

**Additional Information**
- which version of PAM do you use?
I have tried both the last Workshop version and the last Github version
- what is the contents of your PAM config file?
![image](https://user-images.githubusercontent.com/36534723/69006780-7d199780-0934-11ea-904f-378c33aa658b.png)
- what are the console logs
No console error in server side console and client side console
- any other evidence
I have registered a video https://youtu.be/dFm83TWES-I 
The "ttt_pam_toggle_menu" works fine

**Comment by Reispfannenfresser** [comment]
This is not a PAM error.

The rtv configuration file is located in the "GarrysMod/garrysmod/data/pam/" folder and should be changed there. Pam will load this file on startup and ignore what is specified as the default config in the code.

You shouldn't modify the gma file, unless you know what you are doing!

For more information please read the [wiki on configuration](https://github.com/Reispfannenfresser/partly-adequate-mapvote/wiki/RTV-Config)


I case you want to know exactly why what you did doesn't work:
0. Pam checks if there is a config file in "GarrysMod/garrysmod/data/pam/". When it can't find one it generates one and fills in the default values.
1. You changed the gma file, but it had pam already been started once and generated a default config file.
2. Pam was started again and found a config file (the one it created and filled with the defaults)
3. Pam started with the config file it found and therefor had the default config with rtv being disabled

**Comment by Reispfannenfresser** [comment]
The chat no longer activates rtv.
The only way to do so now it via the command.

**Comment by ThePlatinumGhost** [comment]
Ok thanks, I read the Wiki but I misunderstood something
Thanks again
