### ISSUE TITLE
Add setting to delay votescreen to show at the end of the round when forced by rtv

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Reispfannenfresser/partly-adequate-mapvote#6]
(I don't know if this feature is already present, if you can safely close the post)
This feature concerns the TTT mode of course

**Category**
Serverside,Rockthevote, TTT

**Description**
Once the number of people for "rock the vote" has been reached rather than starting the votemap in the middle of the round, it could be done that the votemap is moved to the end of the round

**Motivation**
Because if the minimum number of votes is reached in the middle of the round, the round cannot continue because the votemap opens and in x seconds it changes the map

**Comment by Reispfannenfresser** [comment]
I probably won't implement such a feature as there are 2 reasons why rtv exist.

1. The one you mentioned: When the players want to change the map (e.g.: they got bored), but they don't want the flow of the game to be interrupted.

2. When the map doesn't work for ttt (e.g.: no weapons or missing materials for most players) it would be annoying to have to wait for the end of the round.

Moving the votescreen to the end of the round is better for the first, but worse for the second. Having it pop up immediately is better for the second, while not being as bad for the first.

When players want to finish the round they can use the rtv functionality when the round is over/at the very start of the next round and it won't interrupt the flow of the game. When the players don't want to finish the round they can just use it immediately.

**Comment by ThePlatinumGhost** [comment]
Maybe you could make a cvar? and leave the choice in the data folder, so whoever wants can decide to put the delay

**Comment by Reispfannenfresser** [comment]
Good point :+1: 
This shouldn't be much work to implement and it would fit nicely into the configuration update.
