### ISSUE TITLE
[FEATURE REQUEST] Gamemode vote support

### ISSUE THREAD

**Issue by Sporesirius** [Reispfannenfresser/partly-adequate-mapvote#9]
**Category**
ui, client sided, server sided

**Description**
The possibility to vote also for gamemodes.

**Comment by Reispfannenfresser** [comment]
I don't think it's possible to change the gamemode while the server is running.
Even if it is, i won't implement this as i don't think this feature fits a mapvote addon.

**Comment by Reispfannenfresser** [comment]
Update: It is possible to change the gamemode while the server is running. (changegamemode command)

**Comment by Sporesirius** [comment]
Oh that's sad, I thought this would give normal players the possibility to change the gamemode and the map of the server. Useful for public server with different gamemodes like ttt, prop hunt  etc.

**Comment by Reispfannenfresser** [comment]
I think that I'm going to implement this anyways.

**Comment by Reispfannenfresser** [comment]
The new version of PAM is now released (but may still still be buggy)
I've written another addon which adds Gamemode Vote support to PAM.
Check it out [here](https://github.com/Partly-Adequate/pam-gamemode-voting)
